---
swagger: "2.0"
info:
  description: "This is the book store built for Hypermedia course at Polimi. We have three main entities:\
  \ Book, Author and Event. Through the website, the user can navigate between a selection of books, adding\
  \ them to the personal cart and purchasing them."
  version: "1.0.0"
  title: "Libreggiamo"
  contact:
    email: "alberto.frattini@mail.polimi.it"
  license:
    name: "Apache-2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "polimi-hyp-2019-team-10496529.herokuapp.com"
basePath: "/v2"
tags:
- name: "book"
  description: "A book available in the website"
- name: "author"
  description: "An author that has written some book in the inventory"
- name: "event"
  description: "Event in which some book is presented"
- name: "cart"
  description: "The personal cart of a user"
schemes:
- "https"
paths:
  /books:
    get:
      tags:
      - "book"
      summary: "Books available in the inventory"
      description: "List of books available in the inventory. Two parameters can be used to limit the amount of books returned and to retrieve the books starting from a fixed offset point"
      operationId: "getAllBooks"
      produces:
      - "applications/json"
      parameters:
      - name: "offset"
        in: "query"
        description: "Pagination offset. Default is 0"
        required: false
        type: "integer"
      - name: "limit"
        in: "query"
        description: "Maximum number of items per page. Default is 20 and \
          \ cannot exceed 500."
        required: false
        type: "integer"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/filter:
    get:
      tags:
      - "book"
      summary: "Books available in the inventory after filtering through some parameters"
      description: "List of books available in the inventory. Three parameters are used: title of the book or name of the\
      \ author, genre of the book and theme of the book"
      operationId: "getBooksThroughFilter"
      produces:
      - "applications/json"
      parameters:
      - name: "titleOrAuthor"
        in: "query"
        description: "Title or Author of the book"
        required: false
        type: "string"
      - name: "genre"
        in: "query"
        description: "Book genre"
        required: false
        type: "string"
      - name: "theme"
        in: "query"
        description: "Book theme"
        required: false
        type: "string"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}:
    get:
      tags:
      - "book"
      summary: "Find book by ID"
      description: "Finds the specific book by ISBN in the inventory through the parameter passed in path"
      operationId: "getBookByIsbn"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "string"
      responses:
        200:
          description: "A book in the inventory"
          schema:
            $ref: "#/definitions/Book"
        400:
          description: "Invalid ISBN supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}/similar:
    get:
      tags:
      - "book"
      summary: "Find similar books by Isbn"
      description: "Returns similar books to the one specified in the path"
      operationId: "getBooksBySimilarity"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "ID of book to return"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of Books"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}/reviews:
    get:
      tags:
      - "book"
      summary: "Find book's reviews by Isbn"
      description: "Returns book's reviews based on the Isbn passed in the path"
      operationId: "getReviewsOfBook"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "Isbn of book's reviews to return"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of reviews"
        400:
          description: "Invalid Isbn supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}/authors:
    get:
      tags:
      - "author"
      summary: "Find book's authors by Isbn"
      description: "Returns book's authors based on the Isbn passed in path"
      operationId: "getAuthorsOfBook"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "Isbn of book's authors to return"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of authors"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Author"
        400:
          description: "Invalid Isbn supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /books/{bookIsbn}/events:
    get:
      tags:
      - "event"
      summary: "Find book's events by Isbn"
      description: "Returns book's events based on the Isbn passed in the path"
      operationId: "getEventsOfBook"
      produces:
      - "application/json"
      parameters:
      - name: "bookIsbn"
        in: "path"
        description: "Isbn of book's events to return"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        400:
          description: "Invalid Isbn supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /events:
    get:
      tags:
      - "event"
      summary: "Events available in the website"
      description: "List of all events where the books in the inventory are presented"
      operationId: "getAllEvents"
      produces:
      - "applications/json"
      responses:
        200:
          description: "A collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /events/{eventId}:
    get:
      tags:
      - "event"
      summary: "Find event by ID"
      description: "Returns an event based on the event id passed in the path"
      operationId: "getEventById"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "ID of event to return"
        required: true
        type: "string"
      responses:
        200:
          description: "An event where a book is presented"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /events/filter:
    get:
      tags:
      - "event"
      summary: "Find events by month"
      description: "Returns events of the specified month passed in path"
      operationId: "getEventsByMonth"
      produces:
      - "application/json"
      parameters:
      - name: "month"
        in: "query"
        description: "Month of the events"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of events"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Event"
        400:
          description: "Invalid month supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /authors:
    get:
      tags:
      - "author"
      summary: "Authors that have written some book in the inventory"
      description: "List of all authors in the database"
      operationId: "getAllAuthors"
      produces:
      - "applications/json"
      responses:
        200:
          description: "A collection of authors"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Author"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /authors/{authorId}:
    get:
      tags:
      - "author"
      summary: "Find author by ID"
      description: "Returns an author through the id passed in the path"
      operationId: "getAuthorById"
      produces:
      - "application/json"
      parameters:
      - name: "authorId"
        in: "path"
        description: "ID of author to return"
        required: true
        type: "string"
      responses:
        200:
          description: "An author with a specific id"
          schema:
            $ref: "#/definitions/Author"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /authors/quotes:
    get:
      tags:
      - "quotes"
      summary: "Quotes of the selected author"
      description: "List of quotes of the selected author. The parameter in the query selects the specific author"
      operationId: "getQuotesByAuthorId"
      produces:
      - "applications/json"
      parameters:
      - name: "authorId"
        in: "query"
        description: "Id of the author used to retrieve quotes"
        required: true
        type: "string"
      responses:
        200:
          description: "A collection of quotes"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Book"
  /users/login:
    post:
      tags:
      - "user"
      summary: "Login for an already registered user"
      description: "Login of a user with parameters of x-www-form-urlencoded content-type passed as formData"
      operationId: "login"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful login"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "User"
  /users/signUp:
    post:
      tags:
      - "user"
      summary: "Sign Up for a new user that has never registered"
      description: "SignUp of a user with parameters of x-www-form-urlencoded content-type passed as formData"
      operationId: "signUpUser"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "formData"
        required: true
        type: "string"
      - name: "email"
        in: "formData"
        required: true
        type: "string"
      - name: "password"
        in: "formData"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfull registration"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "User"
  /users/logout:
    get:
      tags:
      - "user"
      summary: "Logout"
      description: "Logout of a user that has already logged in previously"
      operationId: "logout"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successfull logout"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "User"
  /users/isLoggedIn:
    get:
      tags:
      - "user"
      summary: "Check if a user is logged in"
      description: "Tells if there is a user already logged in"
      operationId: "isLoggedIn"
      produces:
      - "application/json"
      responses:
        200:
          description: "A user is logged in"
          schema:
            $ref: "#/definitions/User"
      x-swagger-router-controller: "User"
  /cart:
    get:
      tags:
      - "cart"
      summary: "Retrieves the cart of a specific user from the database"
      description: "Retrieves from the database the cart of a user using a parameter known in the backend"
      operationId: "getCart"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successfull request"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Cart"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Cart"
  /cart/add:
    post:
      tags:
      - "cart"
      summary: "Adds a book to the cart"
      description: "Adds a book to the cart using the Isbn passed in the query"
      operationId: "addToCart"
      produces:
      - "application/json"
      parameters:
      - name: "isbn"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/Cart"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Cart"
  /cart/empty:
    delete:
      tags:
      - "cart"
      summary: "Empty the Cart"
      description: "Deleting all the elements from the cart"
      operationId: "emptyCart"
      produces:
      - "application/json"
      responses:
        200:
          description: "Successfull deletion"
          schema:
            $ref: "#/definitions/Cart"
        404:
          description: "Unexpected error"
      x-swagger-router-controller: "Cart"
definitions:
  Book:
    type: "object"
    required:
    - "ISBN"
    - "title"
    - "price"
    properties:
      ISBN:
        type: "string"
      title:
        type: "string"
      genre:
        type: "string"
      theme:
        type: "string"
      publisher:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "float"
        minimum: 0.01
        maximum: 100000000000000
      status:
        type: "string"
        description: "Book availability in the inventory"
        enum:
        - "available"
        - "out of stock"
    title: "Book"
    description: "A book for sale in the store"
    example:
      ISBN: "8804668040"
      title: "Il deserto dei tartari"
      genre: "Fiction"
      theme: "War"
      publisher: "Mondadori"
      description: "Often likened to Kafka's The Castle, The Tartar Steppe..."
      author: "Dino Buzzati"
      price: 7.1
      status: "available"
  Event:
    type: "object"
    required:
    - "eventName"
    - "bookPresented"
    properties:
      eventName:
        type: "string"
      bookPresented:
        type: "string"
      eventLocation:
        type: "string"
      eventDate:
        type: "string"
      eventDescription:
        type: "string"
    title: "Event"
    description: "An event scheduled in which a book will be presented"
    example:
      eventName: "The tartar steppe presentation"
      bookPresented: "The tartar steppe"
      eventLocation: "Feltrinelli"
      eventDate: "2019-06-20"
      eventDescription: "The event will take place at 18.00. In the first part, the..."
  Author:
    type: "object"
    required:
    - "authorName"
    properties:
      authorName:
        type: "string"
      authorBiography:
        type: "string"
      nationality:
        type: "string"
      birthDate:
        type: "string"
      birthPlace:
        type: "string"
      mainGenre:
        type: "string"
    title: "Author"
    description: "An author of some book in the store"
    example:
      authorName: "Michael Connelly"
      authorBiography: "Michael Connelly was born in..."
      nationality: "American"
      birthDate: "1955-06-22"
      birthPlace: "San Pellegrino, Italy"
      mainGenre: "Fiction"
  User:
    type: "object"
    required:
    - "name"
    - "email"
    - "password"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    title: "User"
    description: "A user of the book store."
    example:
      name: "Mario Rossi"
      email: "example@example.com"
      password: "****"
  Cart:
      type: "object"
      required:
      - "email"
      - "ISBN"
      properties:
        email:
          type: "string"
        ISBN:
          type: "string"
        quantity:
          type: "number"
          format: "integer"
      title: "Cart"
      description: "The cart of a registered user"
      example:
        email: "example@example.com"
        ISBN: "8888888888"
        quantity: 2
